{% set name = "roifile" %}
{% set version = "2026.1.22" %}
{% set sha256 = "5bd6c3c4423505c09adf48769f80681c246738c035518f4aa4153792e4b24176" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - roifile = roifile.roifile:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - roifile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.cgohlke.com/
  summary: Read and write ImageJ ROI format
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Roifile is a Python library to read, write, create, and plot ImageJ ROIs, an undocumented and ImageJ application specific format to store regions of interest, geometric shapes, paths, text, and whatnot for image overlays.
  dev_url: https://github.com/cgohlke/roifile

extra:
  recipe-maintainers:
    - cgohlke
    - csachs
