{% set name = "roifile" %}
{% set version = "2025.5.10" %}
{% set sha256 = "8e5d1f799695ac59f52d4d62bb9016de74ef2493b4d83e24ce7fb25e19f53cce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - roifile = roifile.roifile:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.19.2

test:
  imports:
    - roifile
  commands:
    - roifile

about:
  home: https://github.com/cgohlke/roifile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read and write ImageJ ROI format.
  description: |
    Roifile is a Python library to read, write, create, and plot ImageJ ROIs, an undocumented and ImageJ application specific format to store regions of interest, geometric shapes, paths, text, and whatnot for image overlays.
  doc_url: https://github.com/cgohlke/roifile
  dev_url: https://github.com/cgohlke/roifile

extra:
  recipe-maintainers:
    - csachs
